### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s1-evaluacion-intermedia-desigc#1]
Good job @desigc !!

Here you have some tips to improve it:

- [x] Indent the code to improve readability and avoid bugs
- [x] Move  fonts CSS before main CSS
- [x] Fix the meta title, instead of a sentence about you it should be about the page
- [x] Add links to menu and logo
- [x] Avoid uppercase on HTML, we can transform the text with CSS
- [x] Improve hierarchy adding common styles to body: `font-family`, `font-weight`, `font-size`, `color`, `background-color`.
- [x] Fix the weight of the main title
- [x] Center vertically the menu on tablet version, also you can add them some padding to make them easier to touch.
- [x] Improve your commit messages, in English and imperative. Using the sentence 'final version' is not the best practice, since the future is unpredictable and you may modify things ;)

Let me know if you have any doubts ;)

**Comment by desigc** [comment]
Hi Nasi! 
Thanks so much for you feedback, it was so useful for me. I want to ask you some things because i have some doubt:

-I have not managed to modify the error I had with the style of the font by myself. Finally I had to copy the google fonts link that you used in your exercise. With this link that I put it did not work well and I do not understand it, because it is the same font-family and the same weights.
      https://fonts.google.com/?query=rubik&selection.family=Rubik:400,700

-Is there any command to indentate the css?
-is it good to do the mediaqueries separately as you do in your exercise or is it indifferent?

Thanks again

**Comment by desigc** [comment]
Hi Nasi!

I already found the problem with the Google source, in a hurry I copied the link that was not. I dont need feedback in this point.

Thanks

**Comment by nasivuela** [comment]
Ole!

I have unchecked a couple of points:

- Remove uppercase from HTML, BLOG -> Blog
- Indent the code

To indent CSS, you probably will need an extension on your editor. regarding the media queries, you can do them together or separated. You will find your still, and what works better for you eventually.

Here you have a little challenge to practice a different technique: try to center the main title with flex instead of positions.

**Comment by desigc** [comment]
Hi Nasi!

I just included your corrections and challange in the code. If you have any recommendation for the final evaluation or consider that I should improve something, please let me know.

Thanks again!

**Comment by nasivuela** [comment]
Well done!

![](https://media.giphy.com/media/xUA7biVI7HSb0Wilsk/giphy.gif)
